# for loop
# syntax:
# range(start, end, step)


for i in range(1, 5, 2):
    print(i)

# in Python, i stores the last valid value generated by range()
print(i)   # prints 3


# if we dont pass step, it is 1 by default
# if we dont pass start, it is 0 by default
# range runs from start to end-1


# while loop
# syntax

while i < 5:
    print(i)
    i += 1

# here i becomes 5 before condition fails
print(i)   # prints 5s

# print list using while loop
my_list = ["a", "b", "c", "d"]
i=0
while i < len(my_list):
    print(my_list[i])
    i += 1
    
    
# for loop
# a for below(more like for each) loops is 
# used to iteratre over a sequence (like list, tuple, string) 
# or other iterable objects
list1 = [1, 2, 3, 4, 5]

# is like a for each loop in other languages, it iterates over each item in the 
# list and assigns it to the variable 'item' in each iteration
for item in list1:
    print(item)

# iterating tuple
tuple1 = (10, 20, 30, 40, 50)
for item in tuple1:
    print(item)

# iterating string
string1 = "Hello"
for char in string1:
    print(char)


# IMP 
# for loop with else
# the else block is executed after the for loop completes normally 
# (i.e., it is not terminated by a break statement)
for i in range(3):
    print(i)
else:
    print("Loop completed without break")
    
# break and continue in for loop
for i in range(5):
    if i == 2:
        break   # exits the loop when i is 2
    print(i)
    
    
for i in range(5):
    if i == 2:
        continue    # skips the rest of the loop body when i is 2 and continues with the next iteration
    print(i)
    
# the else keyword is only executed if the loop is not terminated by a break statement.

# for loop with else and break
for i in range(5):
    if i == 2:
        break   # exits the loop when i is 2
    print(i)
else:
    print("Loop completed without break")  # this will not be executed because of the break statement

# will else be executed if we use continue?
for i in range(5):
    if i == 2:
        continue    # skips the rest of the loop body when i is 2 and continues with the next iteration
    print(i)
else:
    print("Loop completed without break") 

# this will be executed because the loop is not terminated by a break statement
    
#IMP pass statement in  loop
# pass statement in for loop
# its like a placeholder for future code, it does nothing when executed
# pass is a nulll statement in python
for i in range(5):
    if i == 2:
        pass    # does nothing, it is a placeholder for future code
    print(i)
    

# for loop which does nothing
for i in range(45):
    pass



# trick to print the a patern using * symbol
#unliek other language we'd need to use nested loops to print this pattern, but in python we can do it in a single loop using string multiplication
# in python also it prints the new line after each print
n=4

for i in range(1,n):
    print((n-i)*" ",end="")
    print(((2*i)-1)*"*",end="")
    print("\n")  # for newline
    


for i in range(1,11):
    print(f"{10-i+1}")
    
    
